# Generated by Django 5.0.3 on 2024-12-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_memeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemeTemplate',
        ),
    ]
